[platformio]
default_envs = cyd
core_dir = .local/platformio

[env:cyd]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
lib_deps =
  lovyan03/LovyanGFX@1.2.28
  bblanchon/ArduinoJson@7.4.3
build_flags = -Wall -Wextra -Wl,--wrap=dhcp_append_extra_opts

[env:cyd-diagnostics]
extends = env:cyd
build_flags = ${env:cyd.build_flags} -DUSAGE_DIAGNOSTICS

[env:native]
platform = native@1.2.1
test_build_src = no
lib_deps =
  throwtheswitch/Unity@2.6.1
  bblanchon/ArduinoJson@7.4.3
build_flags = -std=c++11 -Iinclude
