"""公式配布元からESP32用ルート証明書を更新し、接続先を検証する。"""
from pathlib import Path
import socket
import ssl
import urllib.request

SOURCES = (
    "https://pki.goog/repo/certs/gtsr4.pem",
    "https://letsencrypt.org/certs/isrgrootx1.pem",
    "https://letsencrypt.org/certs/isrg-root-x2.pem",
)


def main() -> None:
    certs = []
    for url in SOURCES:
        with urllib.request.urlopen(url, timeout=30) as response:
            certs.append(response.read().decode("ascii").strip() + "\n")
    pem = "".join(certs)
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    context.load_verify_locations(cadata=pem)
    for host in ("auth.openai.com", "chatgpt.com"):
        with socket.create_connection((host, 443), timeout=20) as connection:
            with context.wrap_socket(connection, server_hostname=host):
                print(f"TLS verified: {host}")
    destination = Path(__file__).resolve().parents[1] / "include" / "trusted-roots.h"
    destination.write_text(
        '// Generated by scripts/update-ca.py; do not edit.\n#pragma once\n'
        'static const char kTrustedRoots[] = R"PEM(\n' + pem + ')PEM";\n',
        encoding="ascii",
    )


if __name__ == "__main__":
    main()
